# Adapted from https://github.com/bevyengine/bevy/blob/main/deny.toml.

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
  "RUSTSEC-2020-0056", # stdweb unmaintained - https://github.com/koute/stdweb/issues/403
  "RUSTSEC-2021-0047", # security issue - https://github.com/gnzlbg/slice_deque/issues/90
  "RUSTSEC-2021-0096", # spirv_headers unmaintained
]
notice = "deny"
unmaintained = "deny"
vulnerability = "deny"
yanked = "deny"

[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "0BSD",
  "BSD-2-Clause",
  "CC0-1.0",
]
copyleft = "deny"
default = "deny"
unlicensed = "deny"

[[licenses.clarify]]
expression = "MIT"
license-files = []
name = "stretch"

[bans]
highlight = "all" 
multiple-versions = "deny" 
wildcards = "allow" # It sees git as wildcard :(
# Certain crates/versions that will be skipped when doing duplicate detection.
skip = [
  {name = "ahash", version = "0.4"},
  {name = "cfg-if", version = "0.1"}, # https://github.com/rustwasm/console_error_panic_hook/pull/18
  {name = "core-foundation", version = "0.6"},
  {name = "core-foundation", version = "0.7"},
  {name = "core-foundation-sys", version = "0.6"},
  {name = "core-foundation-sys", version = "0.7"},
  {name = "core-graphics", version = "0.19"},
  {name = "fixedbitset", version = "0.2"},
  {name = "hashbrown", version = "0.9"},
  {name = "libm", version = "0.1"},
  {name = "mach", version = "0.2"},
  {name = "ndk", version = "0.3"},
  {name = "ndk-glue", version = "0.3"},
  {name = "proc-macro-crate", version = "0.1"},
  {name = "stdweb", version = "0.1"},
]

[sources]
allow-git = ["https://github.com/bevyengine/bevy"]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-git = "deny"
unknown-registry = "deny"
