format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
newline_style = "Unix"
reorder_impl_items = true
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true
